export const CONCEPTS = {
  '3.4.2':   { name: 'Quiet Moves',             short: 'Non-capturing moves that are often strongest', color: '#4a9eff', internal: true },
  '3.4.2.a': { name: 'Prophylaxis',             short: "Preventing your opponent's threats early",    color: '#4a9eff' },
  '3.4.2.b': { name: 'Piece Improvement',       short: 'Moving pieces to better squares',             color: '#4a9eff' },
  '3.4.2.c': { name: 'Quiet Combo Setups',      short: 'Quiet first moves that begin a combination',  color: '#4a9eff' },
  '3.4.2.d': { name: 'Pawn Breaks',             short: 'Pawn moves that open the position',           color: '#4a9eff' },
  '3.4.2.e': { name: 'King Safety',             short: 'Proactive moves to keep your king safe',      color: '#4a9eff' },
  '3.4.2.f': { name: 'Zugzwang / Tempo',        short: 'Moves that force a positional concession',    color: '#4a9eff' },
  '3.3.6':   { name: 'Calculation Depth',       short: 'Calculating multi-move sequences accurately', color: '#e67e22', internal: true },
  '3.3.6.a': { name: 'Short Forcing Sequences', short: 'Seeing 2-3 move forcing combinations',        color: '#e67e22' },
  '3.3.6.b': { name: 'Quiet Setup Tactics',     short: 'Quiet moves that set up a forcing sequence',  color: '#e67e22' },
  '3.3.6.c': { name: 'Deep Calculation',        short: 'Calculating sequences 5+ moves ahead',        color: '#e67e22' },
  '3.3.6.d': { name: 'Defensive Resources',     short: 'Finding saving moves when in trouble',        color: '#e67e22' },
  '3.3.3':   { name: 'Forcing Moves First',     short: 'Checks, captures, and threats before quiet moves', color: '#e74c3c' },
  '3.1.1':   { name: 'Forks',                   short: 'Attacking two pieces at once with one move',  color: '#e74c3c' },
  '3.1.3':   { name: 'Skewers',                 short: 'Forcing a valuable piece to move, winning behind it', color: '#e74c3c' },
  '3.1.4':   { name: 'Discovered Attacks',      short: 'Moving one piece to reveal an attack from another', color: '#e74c3c' },
  '3.1.5':   { name: 'Double Checks',           short: 'Checking with two pieces simultaneously',     color: '#e74c3c' },
  '3.1.6':   { name: 'Zwischenzug',             short: 'An in-between move before the expected reply', color: '#e74c3c' },
  '3.1.7':   { name: 'Pins',                    short: 'A piece cannot move without exposing a more valuable one', color: '#e74c3c' },
  '3.1.8':   { name: 'Overloading',             short: 'Exploiting pieces defending too many things', color: '#e74c3c' },
  '3.1.10':  { name: 'Deflection',              short: 'Forcing a defending piece off its key square', color: '#e74c3c' },
  '3.1.11':  { name: 'Interference',            short: 'Blocking the coordination of opposing pieces', color: '#e74c3c' },
  '3.1.12':  { name: 'Trapped Piece',           short: 'A piece that cannot escape capture',           color: '#e74c3c' },
  '3.1.13':  { name: 'Windmill',                short: 'Repeating check-and-gain sequence',            color: '#e74c3c' },
  '3.1.14':  { name: 'Clearance Sacrifice',     short: 'Giving up material to open a line or square',  color: '#e74c3c' },
  '3.2.1':   { name: 'Back Rank Mate',          short: 'Checkmating on the first or eighth rank',      color: '#e74c3c' },
  '3.2.2':   { name: 'Mating Net',              short: 'Setting up an inescapable checkmate',          color: '#e74c3c' },
  '7.3.1':   { name: 'Tilt',                    short: 'Play drops significantly after a loss',        color: '#9b59b6' },
  '7.1.1':   { name: 'Fatigue',                 short: 'Play deteriorates in long sessions',           color: '#9b59b6' },
  '7.1.2':   { name: 'Late Session Decline',    short: 'Accuracy drops after 2+ hours of play',       color: '#9b59b6' },
  '4.1.4':   { name: 'Pawn Structure',          short: 'Creating or exploiting pawn weaknesses',       color: '#f0c040' },
  '4.1.5':   { name: 'Weak Squares',            short: 'Occupying squares the opponent cannot defend', color: '#f0c040' },
  '4.2.3':   { name: 'Piece Coordination',      short: 'Getting your pieces to work together',        color: '#f0c040' },
  '4.2.4':   { name: 'Space Advantage',         short: 'Controlling more territory on the board',     color: '#f0c040' },
  '4.4.3':   { name: 'King Activity',           short: 'Activating the king in the endgame',          color: '#f0c040' },
  '4.4.5':   { name: 'Pawn Endgames',           short: 'Converting pawn advantages accurately',       color: '#f0c040' },
  '6.1':     { name: 'Opening Principles',      short: 'Development, center control, king safety',    color: '#34495e' },
}

export const conceptName  = code => CONCEPTS[code]?.name  || code
export const conceptShort = code => CONCEPTS[code]?.short || ''
export const conceptColor = code => CONCEPTS[code]?.color || 'var(--accent)'
